version: "3.9"

services:
  db:
    image: postgres:15
    container_name: project3_db
    restart: always
    environment:
      POSTGRES_USER: mahesh
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: project3
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: project3_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://mahesh:password123@db:5432/project3
      SECRET_KEY: supersecretkey
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
